app:
  ip: "0.0.0.0"
  port: "8080"
  db: postgresql # mongodb postgresql
  log: "/app/logs/logfile.log" # логи локально
jwt:
  secret: "g32hv5fx2t6i2572hfc"
  access_cookie: "access_token"
  refresh_cookie: "refresh_token"
grpc:  
  port: 44044  
  timeout: 10h
postgres:
  host:	postgres
  port: 5432
  database: postgres
  username: postgres
  password: 12345
mongo:
  url: "mongodb://mongo:27017/?ssl=false"