version: '3.8'

services:
  app:
    container_name: app-container
    image: tpes
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ..:/TPES
    environment:
      - ENV=development
    depends_on:
      - mongo

  mongo:
        ports:
            - '27017:27017'
        container_name: mongo-container
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            # ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
            # ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
            # ME_CONFIG_MONGODB_URL: mongodb://mongo:12345@mongo:27017/
            ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
        image: mongo
        volumes:
          - mongo-data:/data/db
          #- ./mongod.conf:/etc/mongod.conf

volumes:
  mongo-data:
    driver: local