version: '3.8'

services:
  app:
    container_name: app-container
    image: tpes
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ..:/TPES
    environment:
      - ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_NAME=postgres
    depends_on:
      - postgres
      - mongo

  postgres:
    container_name: postgres-container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  mongo:
        ports:
            - '27017:27017'
        container_name: mongo-container
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            # ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
            # ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
            # ME_CONFIG_MONGODB_URL: mongodb://mongo:12345@mongo:27017/
            ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
        image: mongo
        volumes:
          - mongo-data:/data/db
          #- ./mongod.conf:/etc/mongod.conf

volumes:
  postgres-data:
    # лучше локально
    # driver: local
  mongo-data:
    driver: local